# Generated by Django 2.2.12 on 2024-01-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_reg_empcode_remove_reg_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
