# Generated by Django 2.2.12 on 2024-01-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
