# Generated by Django 2.2.12 on 2024-02-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20240202_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
