# Generated by Django 2.2.12 on 2024-02-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_seleruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleruser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
