# Generated by Django 2.2.12 on 2024-02-09 13:50

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20240209_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg',
        ),
        migrations.AlterModelManagers(
            name='seleruser',
            managers=[
                ('empAuth_object', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Seleruser'),
        ),
    ]
