# Generated by Django 2.2.12 on 2024-02-10 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seler',
        ),
        migrations.DeleteModel(
            name='Seleruser',
        ),
    ]
