# Generated by Django 2.2.12 on 2024-02-12 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('home', '0015_auto_20240210_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seleruser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('fieldproduct', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(related_name='seleruser_groups', to='auth.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(related_name='seleruser_user_permissions', to='auth.Permission')),
            ],
            options={
                'db_table': 'seleruser',
            },
        ),
    ]
