# Generated by Django 2.2.12 on 2024-02-14 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_seleruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Seleruser', to=settings.AUTH_USER_MODEL),
        ),
    ]
