# Generated by Django 2.2.12 on 2024-02-15 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20240214_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Seleruser'),
        ),
    ]
